version: '3'
services:

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
      - "./rabbitmq:/etc/giethoornharbor/"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_CONFIG_FILE=/etc/giethoornharbor/rabbitmq.conf

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    container_name: sqlserver
    hostname: sqlserver
    environment:
      MSSQL_PID: "harbormanager"
      SA_PASSWORD: "Qk22v2PDrxuqLp"
      ACCEPT_EULA: "Y"
    restart: unless-stopped    
    ports:
      - "1433:1433"

  logserver:
    image: datalust/seq:latest
    container_name: logserver
    ports:
      - "5341:80"
    environment:
      - ACCEPT_EULA=Y

  harbormanagementapi:
    image: giethoornharbor/harbormanagementapi:1.0
    build: HarborManagementAPI
    depends_on:
      - rabbitmq
      - sqlservergh
    ports:
      - "5200"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  auditlogservice:
    image: giethoornharbor/auditlogservice:1.0
    build: AuditlogService
    container_name: auditlogservice
    depends_on:
      - rabbitmq
    environment:
      - DOTNET_ENVIRONMENT=Production

volumes:
  sqlserverdata:
    external: true
  rabbitmqdata:
    external: true